### ISSUE TITLE
How do you disable logging?

### ISSUE THREAD

**Issue by zllovesuki** [sensiblecodeio/tiny-ssl-reverse-proxy#38]
It doesn't seem like the CLI takes an argument for `-logging`, and it defaults to true.

**Comment by pwaller** [comment]
* What have you tried so far?
* What unwanted log messages are you seeing, when?
* Have you tried passing `-logging=false`?

**Comment by zllovesuki** [comment]
Okay, `-logging=false` does it. I tried `-logging false` and apparently I don't know my CLI-fu good enough.
